USE lab1;
CREATE TABLE class (
`id` INT PRIMARY KEY AUTO_INCREMENT,
`name` VARCHAR(50)
);
INSERT INTO class (`name`) VALUES ("PARVATHY"), ("KARTHIK"), ("AKKU"), ("MALU");
SELECT * FROM class;

START TRANSACTION;
INSERT INTO class (`name`) VALUES ("BINDU");
ROLLBACK;

INSERT INTO class (`name`) VALUES ("BINDU");
COMMIT;

START TRANSACTION;
SAVEPOINT abc;
INSERT INTO class (`name`) VALUES ("SANTHOSH");
ROLLBACK TO abc;

COMMIT;





