USE lab1;
CREATE TABLE EMPLOYEE (
CODE VARCHAR(20),
NAME CHAR(30),
DOB DATE NOT NULL,
DESIGNATION CHAR(50),
SALARY INT
);
INSERT INTO EMPLOYEE VALUES ('E90','AMITHA','1998-05-24','PEON','30000');
INSERT INTO EMPLOYEE VALUES ('E70','SREE','1996-12-09','CLERK','50000');
INSERT INTO EMPLOYEE VALUES ('E83','MANOJ','1980-12-18','GENERAL MANAGER','75000');
INSERT INTO EMPLOYEE VALUES ('E68','BABU','1972-05-11','SUPERVISOR','60000');
INSERT INTO EMPLOYEE VALUES ('E12','BINDU','1988-07-16','ACCOUNTANT','55000');

DELIMITER $$
CREATE TRIGGER INSERT_PREVENT
BEFORE INSERT
ON EMPLOYEE FOR EACH ROW
BEGIN
IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES TO EMPLOYEE TABLE';
END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER UPDATE_PREVENT
BEFORE UPDATE
ON EMPLOYEE FOR EACH ROW
BEGIN
IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES TO EMPLOYEE TABLE';
END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER DELETE_PREVENT
BEFORE DELETE
ON EMPLOYEE FOR EACH ROW
BEGIN
IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES TO EMPLOYEE TABLE';
END IF;
END $$
DELIMITER ;